# @info
# https://github.community/t5/GitHub-Actions/Start-a-workflow-from-another-workflow/td-p/37586
name: main
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/JamesIves/github-pages-deploy-action#getting-started-airplane
      - name: checkout üõéÔ∏è
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      # https://github.com/denolib/setup-deno
      - uses: denolib/setup-deno@master
        with:
          deno-version: 1.5.4
      - uses: actions/setup-node@v2
        with:
          node-version: 15.0.1
      - name: install
        run: yarn && deno install --unstable -f -A -n rad https://raw.githubusercontent.com/cdaringe/rad/main/src/bin.ts
      - name: test
        run: rad test
      - name: build-ts-artifacts
        run: rad runAndFormat
      - name: compile
        run: npx tsc -p tsconfig.prod.json
      # - name: deploy
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./public

      # release
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
